name: Deploy to Replicate

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2

      - name: Login to Replicate Docker registry
        run: echo "${{ secrets.REPLICATE_API_TOKEN }}" | docker login r8.im -u vibendship --password-stdin

      - name: Push to Replicate
        run: cog push r8.im/vibendship/sketch-to-interior
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
